book/urls.py
from django.urls import path
from . import views

app_name = 'book'

urlpatterns = [
    path('', views.list_books, name='list_books'),
    path('<uuid:pk>/', views.book_detail, name='book_detail'),
    # path('<uuid:pk>/delete', views.delete_book, name='delete_book'),
    path('<uuid:pk>/edit', views.edit_book, name='edit_book'),
    path('add_book', views.add_book, name='add_book'),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

libralink/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('books/', include('book.urls')),
    path('patron/', include('patron.urls')),
    path('transaction/', include('transaction.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

patron/urls.py
from django.urls import path
from . import views

app_name = 'patron'

urlpatterns = [
    path('', views.patron_list, name='patron_list'),
    path('add/', views.add_patron, name='add_patron'),
    path('<uuid:pk>/', views.patron_detail, name='patron_detail'),
    path('<uuid:pk>/edit/', views.edit_patron, name='edit_patron'),
    path('<uuid:pk>/deactivate/', views.deactivate_patron,
         name='deactivate_patron'),
]

transaction/urls.py
from django.urls import path
from . import views

app_name = 'transaction'

urlpatterns = [
    path('<uuid:book_pk>/checkout/', views.transaction_checkout, name='checkout'),
    path('<uuid:book_pk>/return/', views.start_return_process, name='return'),
    # path('<uuid:book_pk>/return/select_return_transaction',
    #      views.select_return_transaction, name='select_return_transaction'),
    path('return_success/', views.return_success, name='return_success'),
    path('transactions/', views.transaction_list, name='transaction_list')
]

core/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    librarian_id = models.CharField(
        max_length=8, primary_key=True, unique=True)
    email = models.EmailField(max_length=200, unique=True)

core/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'librarian_id',
                  'email', 'password1', 'password2')


class CustomAuthenticationForm(AuthenticationForm):
    librarian_id = forms.CharField(
        max_length=8, required=True, label='Librarian ID')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'autofocus': True})
        # Define the order of fields
        self.order_fields(['username', 'librarian_id', 'password'])

    def confirm_login_allowed(self, user):
        super().confirm_login_allowed(user)
        librarian_id_form = self.cleaned_data['librarian_id']
        if not user.librarian_id == librarian_id_form:
            raise forms.ValidationError(
                "Incorrect librarian ID.", code='invalid_librarian_id')

    # def __init__(self, *args, **kwargs):
    #     super(CustomAuthenticationForm, self).__init__(*args, **kwargs)
    #     self.order_fields(['username', 'librarian_id', 'password'])

core/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import render, redirect
from django.urls import reverse

from .forms import CustomAuthenticationForm, CustomUserCreationForm
from book.models import Book
from patron.models import Patron
from transaction.models import Transaction


@login_required
def dashboard(request):
    """ Display the dashboard page for logged-in users. """
    books = Book.objects.all()
    patrons = Patron.objects.all()
    transactions = Transaction.objects.all()
    return render(request, 'core/dashboard.html', {'books': books, 'patrons': patrons, 'transactions': transactions})


def register(request):
    """ Handle user registration. """
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Registration successful.")
            return redirect(reverse('core:dashboard'))
        else:
            messages.error(
                request, "Registration failed. Please correct the errors below.")

    else:
        form = CustomUserCreationForm()

    return render(request, 'core/register.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            librarian_id = form.cleaned_data.get('librarian_id')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username,
                                password=password, librarian_id=librarian_id)
            if user is not None:
                login(request, user)
                messages.info(
                    request, f"You are now successfully logged in as {username}.")
                return redirect('core:dashboard')
            else:
                messages.error(request, "Invalid Credentials.")
        else:
            messages.error(request, "Invalid Credentials.")

    else:
        form = CustomAuthenticationForm()

    return render(request, 'core/login.html', {'form': form})


def logout_view(request):
    """ Handle user logout. """
    logout(request)
    messages.success(request, "You have successfully logged out.")
    return redirect('core:login')

core/templates/core/dashboard.html
{% extends 'main.html' %}
{% block title %}Dashboard{% endblock %}

{% block content %}
{% if messages %}
            <div class='text-center'>
                {% for message in messages %}
                    <p>{{ message }}</p>
                {% endfor %}
            </div>
{% endif %}
<section class='mt-16 mb-16'>
    {% comment %} <h1 class='text-xl'>Welcome {{ request.user|title }}!</h1> {% endcomment %}
    <h1 class='text-5xl mb-6'>Welcome to LibraLink!</h1>
    <p>
        Greetings, {{request.user|title}}! Welcome to your central hub for managing our library's collections and services. Here, you can efficiently add new books, update current listings, oversee patron activities, and monitor loan transactions. Our system is designed to streamline your daily tasks and enhance our library's operations. Let's ensure a seamless and enriching experience for all our patrons together.
    </p>

    <div>
        <h2 class='mt-6 mb-6 text-3xl'>Quick Links</h2>

        <div class='w-full h-fit p-6 rounded-md bg-slate-400'>
            <h3 class="uppercase text-2xl font-medium mb-4">Books</h3>
            <ul class="list-inside list-disc">
                <li><a href="{% url 'book:add_book' %}" class="hover:text-slate-700 hover:font-semibold">Add Book</a></li>
                <li>
                    <p class="inline-block cursor-pointer hover:text-slate-700 hover:font-semibold" onclick="showBooksOnLoan()">Books on Loan</p>
                    <div class="js-books-on-loan"></div>                
                </li>
                <li>
                    <p class="inline-block hover:text-slate-700 hover:font-semibold cursor-pointer" onclick="showOutOfStockBooks()">Out of Stock Books</p>
                    <div class="js-out-of-stock-books"></div> 
                </li>
            </ul>
        </div>

        <div class='mt-6 w-full h-fit p-6 rounded-md bg-slate-400'>
            <h3 class="uppercase text-2xl font-medium mb-4">Patrons</h3>
            <ul class="list-inside list-disc">
                <li><a href="{% url 'patron:add_patron' %}" class="hover:text-slate-700 hover:font-semibold">Add Patron</a></li>
                <li>
                    <p class="inline-block cursor-pointer hover:text-slate-700 hover:font-semibold" onclick="showRedPatrons()">Red Patrons</p>
                    <div class="js-red-patrons"></div>                
                </li>
            </ul>
        </div>

        <div class='mt-6 w-full h-fit p-6 rounded-md bg-slate-400'>
            <h3 class="uppercase text-2xl font-medium mb-4">Transactions</h3>
            <ul class="list-inside list-disc">
                <li><a href="{% url 'transaction:transaction_list' %}" class="hover:text-slate-700 hover:font-semibold">All Transactions</a></li>
                <li>
                    <p class="inline-block cursor-pointer hover:text-slate-700 hover:font-semibold" onclick="showPendingReturns()">Pending Returns</p>
                    <div class="js-pending-returns"></div>                
                </li>
            </ul>
        </div>
    </div>
</section>

<script>
    let booksOnLoanVisible = false;
    let outOfStockBooksVisible = false;
    let redPatronsVisible = false;
    let pendingReturnsVisible = false;


    function showPendingReturns() {
        const divElement = document.querySelector('.js-pending-returns')
        if (!pendingReturnsVisible) {
            divElement.innerHTML = `
            <ul class="mt-4 mb-4 bg-slate-300 p-4 rounded-md font-medium">
                {% for transaction in transactions %}
                    {% if transaction.is_returned == False %}
                        <li class="mb-2"> » <a href="{% url 'patron:patron_detail' transaction.patron.id %}">{{transaction.patron}}</a> | <a href="{% url 'book:book_detail' transaction.book.id %}">{{transaction.book}}</a> </li>
                    {% endif %}
                {% endfor %} 
            </ul> 
            `
        } else {
            divElement.innerHTML = ''
        }
        pendingReturnsVisible = !pendingReturnsVisible
    }

    function showRedPatrons() {
        const divElement = document.querySelector('.js-red-patrons')
        if (!redPatronsVisible) {
            divElement.innerHTML = `
            <ul class="mt-4 mb-4 bg-slate-300 p-4 rounded-md font-medium text-rose-600">
                {% for patron in patrons %}
                    {% if patron.status == 'red' %}
                        <li class="mb-2"> » <a href="{% url 'patron:patron_detail' patron.id %}">{{patron}}</a> </li>
                    {% endif %}
                {% endfor %} 
            </ul> 
            `
        } else {
            divElement.innerHTML = ''
        }
        redPatronsVisible = !redPatronsVisible
    }
    function showBooksOnLoan() {
        const divElement = document.querySelector('.js-books-on-loan')
        if (!booksOnLoanVisible) {
            divElement.innerHTML = `
                <ul class="mt-4 mb-4 bg-slate-300 p-4 rounded-md font-medium">
                    {% for book in books %}
                        {% if book.copies_on_loan > 0 %}
                            <li class="mb-2"> » <a href="{% url 'book:book_detail' book.id %}">{{book}}</a> </li>
                        {% endif %}
                    {% endfor %} 
                </ul>            
                `
        } else {
            divElement.innerHTML = ''
        }
        booksOnLoanVisible = !booksOnLoanVisible        
        }

    function showOutOfStockBooks() {
        const divElement = document.querySelector('.js-out-of-stock-books')
        if (!outOfStockBooksVisible){
            divElement.innerHTML = `
                <ul class="mt-4 mb-4 bg-slate-300 p-4 rounded-md font-medium">
                    {% for book in books %}
                        {% if book.available_copies <= 0 %}
                            <li> » <a href="{% url 'book:book_detail' book.id %}">{{book}}</a> </li>
                        {% endif %}
                    {% endfor %} 
                </ul>            
            `    
        } else {
            divElement.innerHTML = ''
        }
        outOfStockBooksVisible = !outOfStockBooksVisible       
    }
</script> 
    
{% endblock %}

core/templates/core/login.html
{% extends 'main.html' %}
{% block title %}Login{% endblock %}

{% block content %}
{% load widget_tweaks %}
<div class='flex items-center justify-center min-h-screen'>
    <div class="flex flex-col items-center w-full">
        <h1 class='text-4xl font-bold mb-6'>Login</h1>
        <div class='py-8 px-8 w-2/3 lg:w-1/3 bg-slate-400 mx-auto rounded'>
            {% if messages %}
            <div class='text-center'>
                {% for message in messages %}
                    <p>{{ message }}</p>
                {% endfor %}
            </div>
            {% endif %}

            <form method='POST'>
                {% csrf_token %}
                {% for field in form %}
                    <div class="block text-slate-900 font-bold mb-2">
                        {{ field.label_tag }}
                    </div>
                    {% render_field field class+='py-2 px-2 mb-4 bg-stone-100 w-full rounded'%}
                    {% for error in field.errors %}
                        <div class="text-rose-600">{{ error }}</div>
                    {% endfor %}
                {% endfor %}
                <button type='submit' class='py-2 px-6 bg-slate-900 rounded text-stone-100 hover:bg-slate-950'> Login </button>
            </form>
            <p class='mt-4'>No account? Register <a href='{% url 'core:register' %}' class='font-bold hover:text-stone-300'>here</a>.</p>
        </div>
    </div>
</div>

{% endblock %}

core/templates/core/register.html
{% extends 'main.html' %}
{% block title %}Register{% endblock %}

{% block content %}
{% load widget_tweaks %}
<div class='flex items-center justify-center min-h-screen'>
    <div class="flex flex-col items-center w-full">
        <h1 class='text-4xl font-bold mb-6'>Register</h1>
        <div class='py-8 px-8 w-2/3 lg:w-1/3 bg-slate-400 mx-auto rounded'>
            <form method='POST'>
                {% csrf_token %}
                {% for field in form %}
                    <div class="block text-slate-900 font-bold mb-2">
                        {{ field.label_tag }}
                    </div>
                    {% render_field field class+='py-2 px-2 mb-4 bg-stone-100 w-full rounded'%}
                    {% for error in field.errors %}
                        <div class="text-rose-600">{{ error }}</div>
                    {% endfor %}
                {% endfor %}
                
                <button type='submit' class='mt-4 py-2 px-6 bg-slate-900 rounded text-stone-100 hover:bg-slate-950'> Register </button>
            </form>
            <p class='mt-4'>Already have an account? Login <a href='{% url 'core:login' %}' class=' font-bold hover:text-stone-300'>here</a>.</p>
        </div>
    </div>
</div>

{% endblock %}