book/urls.py
from django.urls import path
from . import views

app_name = 'book'

urlpatterns = [
    path('', views.list_books, name='list_books'),
    path('<uuid:pk>/', views.book_detail, name='book_detail'),
    # path('<uuid:pk>/delete', views.delete_book, name='delete_book'),
    path('<uuid:pk>/edit', views.edit_book, name='edit_book'),
    path('add_book', views.add_book, name='add_book'),
]

libralink/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('books/', include('book.urls')),
    path('patron/', include('patron.urls')),
    path('transaction/', include('transaction.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

patron/urls.py
from django.urls import path
from . import views

app_name = 'patron'

urlpatterns = [
    path('', views.patron_list, name='patron_list'),
    path('add/', views.add_patron, name='add_patron'),
    path('<uuid:pk>/', views.patron_detail, name='patron_detail'),
    path('<uuid:pk>/edit/', views.edit_patron, name='edit_patron'),
    path('<uuid:pk>/deactivate/', views.deactivate_patron,
         name='deactivate_patron'),
]

transaction/urls.py
from django.urls import path
from . import views

app_name = 'transaction'

urlpatterns = [
    path('<uuid:book_pk>/checkout/', views.transaction_checkout, name='checkout'),
    path('<uuid:book_pk>/return/', views.start_return_process, name='return'),
    # path('<uuid:book_pk>/return/select_return_transaction',
    #      views.select_return_transaction, name='select_return_transaction'),
    path('return_success/', views.return_success, name='return_success'),
    path('transactions/', views.transaction_list, name='transaction_list')
]

patron/models.py
from django.db import models
import uuid


class Patron(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=200)
    email = models.EmailField(unique=True)
    membership_id = models.CharField(max_length=50, unique=True)
    late_returns = models.PositiveIntegerField(default=0)
    pending_return = models.PositiveIntegerField(default=0)
    PATRON_STATUS_CHOICES = [
        ('green', 'Green'),
        ('yellow', 'Yellow'),
        ('red', 'Red'),
    ]

    status = models.CharField(
        max_length=100, choices=PATRON_STATUS_CHOICES, default='green')

    ACCOUNT_STATUS_CHOICES = [
        ('active', 'Active'),
        ('deactivated', 'Deactivated')
    ]

    account_status = models.CharField(
        max_length=100, choices=ACCOUNT_STATUS_CHOICES, default='active')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']

patron/forms.py
from django import forms
from .models import Patron


class PatronForm(forms.ModelForm):
    class Meta:
        model = Patron
        fields = ['name', 'email', 'membership_id', 'status', 'account_status']

patron/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse

from .models import Patron
from .forms import PatronForm
from transaction.models import Transaction


@login_required
def patron_list(request):
    query = request.GET.get('q', '')
    if query:
        patrons = Patron.objects.filter(
            Q(name__icontains=query) |
            Q(email__icontains=query) |
            Q(membership_id__icontains=query) |
            Q(status__icontains=query) |
            Q(account_status__icontains=query)
        )
        if not patrons.exists():
            messages.error(
                request, 'No patrons found matching the search criteria.')
    else:
        patrons = Patron.objects.all()

    paginator = Paginator(patrons, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'patron/patron_list.html', {'patrons': patrons, 'page_obj': page_obj})


@login_required
def add_patron(request):
    if request.method == 'POST':
        form = PatronForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'New Patron was successfully added.')
            return redirect('patron:patron_list')
        else:
            messages.error(
                request, 'Invalid input. Please check the errors below.')
    else:
        form = PatronForm()

    return render(request, 'patron/add_patron.html', {'form': form})


@login_required
def patron_detail(request, pk):
    patron = get_object_or_404(Patron, pk=pk)
    transactions = Transaction.objects.filter(patron=patron)
    paginator = Paginator(transactions, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'patron/patron_detail.html', {'patron': patron, 'transactions': transactions, 'page_obj': page_obj})


@login_required
def edit_patron(request, pk):
    patron = get_object_or_404(Patron, pk=pk)
    if request.method == 'POST':
        form = PatronForm(request.POST, instance=patron)
        if form.is_valid():
            form.save()
            messages.success(request, 'Patron was edited successfully.')
            return redirect(reverse('patron:patron_detail', args=[pk]))
        else:
            messages.error(
                request, 'Invalid input. Please check the errors below.')
    else:
        form = PatronForm(instance=patron)

    return render(request, 'patron/edit_patron.html', {'form': form, 'patron': patron_detail})


@login_required
def deactivate_patron(request, pk):
    patron = get_object_or_404(Patron, pk=pk)
    patron.account_status = 'deactivated'
    patron.status = 'red'
    patron.save()
    messages.info(request, 'Patron account has been deactivated.')
    return redirect(reverse('patron:patron_detail', args=[pk]))

patron/templates/patron/add_patron.html
{% extends 'main.html' %}
{% block title %}Add Patron{% endblock %}

{% block content %}
{% load widget_tweaks %}
<div class='flex items-center justify-center min-h-screen mb-16'>
    <div class="flex flex-col items-center w-full">
        <h1 class='mt-8 text-4xl font-bold mb-6'>Add Patron</h1>
        {% if messages %}
            {% for message in messages %}
            <p class='text-rose-400'>{{message}}</p>
            {% endfor %}
        {% endif %}
        <div class='py-8 px-8 w-[80%] lg:w-[40%] bg-slate-400 mx-auto rounded'>
            <form method='POST'>
                {% csrf_token %}
                {% for field in form %}
                    <p class="block text-slate-900 font-bold mb-2">{{field.label_tag}}</p>
                    {% render_field field class+='py-2 px-2 mb-4 bg-stone-100 w-full rounded'%}

                    {% for error in field.errors %}
                        <p class='text-rose-600'>{{error}}</p>
                    {% endfor %}
                {% endfor %}
                <button type='submit' class='py-2 px-6 bg-slate-900 rounded text-stone-100 hover:bg-slate-950'> Add Patron </button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

patron/templates/patron/edit_patron.html
{% extends 'main.html' %}
{% block title %}Edit Patron{{patron.name}}{% endblock %}

{% block content %}
{% load widget_tweaks %}
<div class='flex items-center justify-center min-h-screen mb-16'>
    <div class="flex flex-col items-center w-full">
        <h1 class='mt-8 text-4xl font-bold mb-6'>Edit Patron</h1>
        <div class='py-8 px-8 w-2/3 lg:w-1/3 bg-slate-400 mx-auto rounded'>
            <form method='POST'>
                {% csrf_token %}
                {% for field in form %}
                    <p class="block text-slate-900 font-bold mb-2">{{field.label_tag}}</p>
                    {% render_field field class+='py-2 px-2 mb-4 bg-stone-100 w-full rounded'%}

                    {% for error in field.errors %}
                        <p class='text-rose-600'>{{error}}</p>
                    {% endfor %}
                {% endfor %}
                <button type='submit' class='py-2 px-6 bg-slate-900 rounded text-stone-100 hover:bg-slate-950'> Save Changes </button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

patron/templates/patron/patron_detail.html
{% extends 'main.html' %}
{% block title %}{{patron.name}}{% endblock %}

{% block content %}
<div class="mt-16">
    <h1 class='text-2xl mb-4'>{{patron.name}}</h1>
    {% if messages %}
        {% for message in messages %}
            <p class='text-emerald-600 mb-2'>{{message}}</p>
        {% endfor %}
    {% endif %}

    {% if patron.status == 'green' %}            
        <p><span class='font-medium'>Status: </span><span class='font-semibold text-emerald-600'>Green Patron</p>
    {% elif patron.status == 'yellow' %}
        <p><span class='font-medium'>Status: </span><span class='font-semibold text-yellow-600'>Yellow Patron</p>
    {% elif patron.status == 'red' %}
        <p><span class='font-medium'>Status: </span><span class='font-semibold text-rose-600'>Red Patron</p>
    {% endif %}
    <p><span class='font-medium'>Account Status: </span>{{patron.account_status|title}}</p>
    <p><span class='font-medium'>Late Returns: </span>{{patron.late_returns}}</p>
    <p><span class='font-medium'>Email: </span>{{patron.email}}</p>
    <p><span class='font-medium'>Membership ID: </span>{{patron.membership_id}}</p>
    <div class='mt-4 flex space-x-2'>
        {% if patron.account_status == "active" %}
        <a href="{% url 'patron:deactivate_patron' patron.id %}" class='inline-block py-2 px-4 bg-rose-500 hover:bg-rose-700 text-white rounded'>Deactivate Member</a>
        {% endif %}
        <a href="{% url 'patron:edit_patron' patron.id %}" class='inline-block py-2 px-4 bg-slate-700 hover:bg-slate-900 text-white rounded'>Edit</a>
    </div>
    
    <hr class='border-black my-8'>
</div>

<div>
    <h2 class='text-3xl'>Pending Returns: {{ patron.pending_return }}</h2>
    <div class='mt-2'>
        {% for transaction in transactions %}
            {% if transaction.is_returned == False %}
                <p><span class='text-slate-950 font-medium'>Book:</span> <a href="{% url 'book:book_detail' transaction.book.id %}" class='text-slate-500 hover:font-medium'>{{transaction.book}}</a></p>
                <p><span class='text-slate-950 font-medium'>Date Borrowed:</span> {{transaction.date_borrowed}}</p>
                <p><span class='text-slate-950 font-medium'>Date Due:</span> {{transaction.date_due}}</p>
                <a href="{% url 'transaction:return' transaction.book.id %}" class='inline-block mt-4 py-2 px-4 bg-slate-700 hover:bg-slate-900 rounded text-white'>Return a Copy</a>
                <br>
            {% endif %}
        {% endfor %}
    </div>
    <hr class='border-black my-8'>
</div>

<div>
    <h2 class='text-3xl'>Borrowing History</h2>
    <div class='mt-4'>
        {% for transaction in page_obj %}
        <p><span class='text-slate-950 font-medium'>Book:</span> <a href="{% url 'book:book_detail' transaction.book.id %}" class='text-slate-500 hover:font-medium'>{{transaction.book}}</a></p>
            <p><span class='text-slate-950 font-medium'>Transaction ID:</span> {{transaction.id}}</p>
            <br>
        {% endfor %}
    </div>
    <div id='pagination' class="flex justify-between mt-10 mb-10">
        {% if page_obj.has_previous %}
            <div class='space-x-4'>
                <a href="?page=1">« first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            </div>                    
        {% endif %}
    
        <span>
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </span>
    
        {% if page_obj.has_next %}
            <div class='space-x-4'>
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last »</a>
            </div>
        {% endif %}
    </div>
</div>
{% endblock %}

patron/templates/patron/patron_list.html
{% extends 'main.html' %}
{% block title %}Patrons{% endblock %}
{% comment %} {% block username %}{% endblock %} {% endcomment %}

{% block content %}

<h1 class='mt-16 mb-4 text-3xl'>Our Patrons</h1>
<a href="{% url 'patron:add_patron' %}" class='inline-block mt-4 mb-8 py-2 px-6 text-white bg-teal-700 hover:bg-teal-900 rounded'>Add Patron</a>
{% if messages %}
    {% for message in messages %}
        <p class='font-semibold'>{{ message }}</p>
    {% endfor %}
{% endif %}
<section class='mt-4 mb-10 flex flex-col lg:flex-row lg:justify-between'>
    
    <section class='w-full lg:w-2/3 mt-4'>
        {% for patron in page_obj %}
            {% if patron.status == 'green' %}            
                <a href="{% url 'patron:patron_detail' patron.pk %}" class='inline-block px-2 bg-emerald-400 rounded text-lg font-medium'>{{patron.name}}</a>
            {% elif patron.status == 'yellow' %}
                <a href="{% url 'patron:patron_detail' patron.pk %}" class='inline-block px-2 bg-yellow-400 rounded text-lg font-medium'>{{patron.name}}</a>
            {% elif patron.status == 'red' %}
                <a href="{% url 'patron:patron_detail' patron.pk %}" class='inline-block px-2 bg-rose-400 rounded text-lg font-medium'>{{patron.name}}</a>
            {% endif %}
            <p>{{patron.email}}</p>
            <p>{{patron.membership_id}}</p>

            <hr class='border-black my-4'>           
        {% endfor%}
        <div id='patrons-pagination' class='flex justify-between mt-10 mb-10'>
            {% if page_obj.has_previous %}
                <div>
                    <a href="?page=1">« first</a>
                    <a href="?page={{page_obj.previous_page_number}}">previous</a>
                </div>
            {% endif %}
                <div><p>Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}</p></div>
            {% if page_obj.has_next  %}
                <div>
                    <a href="?page={{page_obj.next_page_number}}">next</a>
                    <a href="?page={{page_obj.paginator.num_pages}}">last »</a>
                </div>
            {% endif %}
        </div>
    </section>

    <section class='w-full lg:w-1/4'>
        <div>
            <h2 class='text-2xl'>Search</h2>
            <form action="" method="GET">
                <input type="text" name='q' placeholder="Enter patron's name..." value='{{request.GET.q}}' class='w-full bg-slate-300 mt-2 py-2 px-2 rounded'>
            </form>
        </div>

        <div class='mt-6'>
            <h2 class='text-2xl mb-4'>Browse by Rank</h2>
            <a href="{% url 'patron:patron_list' %}?q=green" class='inline-block py-2 px-2 mb-2 bg-emerald-400 rounded'>Green Patron</a>
            <a href="{% url 'patron:patron_list' %}?q=yellow" class='inline-block py-2 px-2 mb-2 bg-yellow-400 rounded'>Yellow Patron</a>
            <a href="{% url 'patron:patron_list' %}?q=red" class='inline-block py-2 px-2 bg-rose-400 rounded'>Red Patron</a>
        </div>

        <div class='mt-6'>
            <h2 class='text-2xl mb-4'>Browse by Account Status</h2>
            <ul class='mt-4 list-disc list-inside'>
                <li><a href='{% url "patron:patron_list" %}?q=active' class='hover:text-slate-500 hover:font-medium'>Active Member</a></li>
                <li><a href='{% url "patron:patron_list" %}?q=deactivated' class='hover:text-slate-500 hover:font-medium'>Deactivated Member</a></li>
            </ul>
        </div>
    </section>
</section>
    
{% endblock %}