book/urls.py
from django.urls import path
from . import views

app_name = 'book'

urlpatterns = [
    path('', views.list_books, name='list_books'),
    path('<uuid:pk>/', views.book_detail, name='book_detail'),
    # path('<uuid:pk>/delete', views.delete_book, name='delete_book'),
    path('<uuid:pk>/edit', views.edit_book, name='edit_book'),
    path('add_book', views.add_book, name='add_book'),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

libralink/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('books/', include('book.urls')),
    path('patron/', include('patron.urls')),
    path('transaction/', include('transaction.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

patron/urls.py
from django.urls import path
from . import views

app_name = 'patron'

urlpatterns = [
    path('', views.patron_list, name='patron_list'),
    path('add/', views.add_patron, name='add_patron'),
    path('<uuid:pk>/', views.patron_detail, name='patron_detail'),
    path('<uuid:pk>/edit/', views.edit_patron, name='edit_patron'),
    path('<uuid:pk>/deactivate/', views.deactivate_patron,
         name='deactivate_patron'),
]

transaction/urls.py
from django.urls import path
from . import views

app_name = 'transaction'

urlpatterns = [
    path('<uuid:book_pk>/checkout/', views.transaction_checkout, name='checkout'),
    path('<uuid:book_pk>/return/', views.start_return_process, name='return'),
    # path('<uuid:book_pk>/return/select_return_transaction',
    #      views.select_return_transaction, name='select_return_transaction'),
    path('return_success/', views.return_success, name='return_success'),
    path('transactions/', views.transaction_list, name='transaction_list')
]

templates/main.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en" class="scroll-smooth">
    
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock %} | LibraLink</title>
    <script src="https://cdn.tailwindcss.com"></script>
    {% tailwind_css %}
</head>
<body class="bg-stone-200">
    <nav class="height-fit py-4 bg-slate-950 px-5 lg:px-16 flex justify-between items-center drop-shadow-xl">
        <a href="/" class="text-xl lg:text-3xl text-white">LibraLink</a>
        <div class="hidden text-lg lg:flex flex-col lg:flex-row items-center lg:items-center space-y-5 lg:space-y-0 lg:gap-8">
            <a href="{% url 'book:list_books' %}" class="text-white hover:text-stone-300">Books</a>
            <a href="{% url 'patron:patron_list' %}" class="text-white hover:text-stone-300">Patrons</a>
            <a href="{% url 'transaction:transaction_list' %}" class="text-white hover:text-stone-300">Transactions</a>
            {% if request.user.is_authenticated %}
            <a href="{% url 'core:logout' %}" class="bg-stone-600 py-2 px-4 rounded text-white hover:bg-stone-800">Logout</a>
            {% endif %}
        </div>
        <span class="duration-500 js-mobile-nav-burger text-white lg:hidden cursor-pointer">&#9776;</span>
    </nav>
    <div class="hidden js-mobile-nav duration-500">
        <div class="duration-500 height-[w-50%] py-6 px-5 bg-slate-950 flex flex-col items-end text-right gap-6">
            <a href="{% url 'book:list_books' %}" class="text-white hover:text-stone-300">Books</a>
            <hr class="w-full border-slate-800">
            <a href="{% url 'patron:patron_list' %}" class="text-white hover:text-stone-300">Patrons</a>
            <hr class="w-full border-slate-800">
            <a href="{% url 'transaction:transaction_list' %}" class="text-white hover:text-stone-300">Transactions</a>
            <hr class="w-full border-slate-800">
            {% if request.user.is_authenticated %}
            <a href="{% url 'core:logout' %}" class="bg-stone-600 w-fit py-2 px-6 rounded text-white hover:bg-stone-800">Logout</a>
            {% endif %}
        </div>    
    </div>
    
    
    <main class="px-5 lg:px-16 min-h-screen">{% block content %}{% endblock %}</main>
    <footer class="bg-slate-900 py-4 text-center">
        <p class="px-5 lg:px-16 text-white">
            © 2024 LibraLink | Designed and Developed by Riza May Largadas
        </p>
    </footer>
    <script>
        const mobileNavBurgerElement = document.querySelector(".js-mobile-nav-burger");
        const mobileNavElement = document.querySelector(".js-mobile-nav")
        mobileNavBurgerElement.addEventListener('click', () => {
            if (mobileNavElement.classList.contains('hidden')) {
                mobileNavElement.classList.remove('hidden');
            } else {
                mobileNavElement.classList.add('hidden');
            }
            
        });
    </script>
</body>
</html>