book/urls.py
from django.urls import path
from . import views

app_name = 'book'

urlpatterns = [
    path('', views.list_books, name='list_books'),
    path('<uuid:pk>/', views.book_detail, name='book_detail'),
    # path('<uuid:pk>/delete', views.delete_book, name='delete_book'),
    path('<uuid:pk>/edit', views.edit_book, name='edit_book'),
    path('add_book', views.add_book, name='add_book'),
]

libralink/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('books/', include('book.urls')),
    path('patron/', include('patron.urls')),
    path('transaction/', include('transaction.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

patron/urls.py
from django.urls import path
from . import views

app_name = 'patron'

urlpatterns = [
    path('', views.patron_list, name='patron_list'),
    path('add/', views.add_patron, name='add_patron'),
    path('<uuid:pk>/', views.patron_detail, name='patron_detail'),
    path('<uuid:pk>/edit/', views.edit_patron, name='edit_patron'),
    path('<uuid:pk>/deactivate/', views.deactivate_patron,
         name='deactivate_patron'),
]

transaction/urls.py
from django.urls import path
from . import views

app_name = 'transaction'

urlpatterns = [
    path('<uuid:book_pk>/checkout/', views.transaction_checkout, name='checkout'),
    path('<uuid:book_pk>/return/', views.start_return_process, name='return'),
    # path('<uuid:book_pk>/return/select_return_transaction',
    #      views.select_return_transaction, name='select_return_transaction'),
    path('return_success/', views.return_success, name='return_success'),
    path('transactions/', views.transaction_list, name='transaction_list')
]

book/models.py
from django.db import models
import uuid


class Book(models.Model):
    id = models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False)
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=200)
    book_cover = models.ImageField(
        upload_to='book_covers/',
        default='default_images/default_book_cover.png',
        blank=True, null=True
    )
    description = models.TextField(null=True, blank=True)
    isbn = models.CharField(max_length=200, unique=True)
    publisher = models.CharField(max_length=200)
    genre = models.CharField(max_length=200)
    available_copies = models.IntegerField()
    copies_on_loan = models.PositiveIntegerField(
        null=True, blank=True, default=0)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['title']

book/forms.py
from django import forms

from .models import Book


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'author', 'isbn', 'publisher',
                  'genre', 'available_copies', 'description', 'book_cover']

book/views.py
from django.db.models import Q
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.urls import reverse
from django.shortcuts import render, redirect, get_object_or_404

from .forms import BookForm
from .models import Book
from transaction.models import Transaction


@login_required
def list_books(request):
    """ Display a list of books, optionally filtered by a search query. """
    query = request.GET.get('q', '').replace('-', ' ')
    if query:
        books = Book.objects.filter(
            Q(title__icontains=query) |
            Q(author__icontains=query) |
            Q(genre__icontains=query) |
            Q(isbn__icontains=query)
        )
        if not books.exists():
            messages.error(request, "No books found!")
    else:
        books = Book.objects.all()

    paginator = Paginator(books, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'book/list_books.html', {'books': books, 'page_obj': page_obj})


@login_required
def book_detail(request, pk):
    """ Display the details of a single book, along with its related transactions. """
    book = Book.objects.get(pk=pk)
    transactions = Transaction.objects.filter(book=book)
    return render(request, 'book/book_detail.html', {'book': book, 'transactions': transactions})


@login_required
def add_book(request):
    """ Add a new book to the database. """
    if request.method == 'POST':
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('book:list_books')
        else:
            messages.error(request, 'Invalid Input.')
            return render(request, 'book/add_book.html')
    else:
        form = BookForm()
        return render(request, 'book/add_book.html', {'form': form})


@login_required
def edit_book(request, pk):
    """ Edit the details of an existing book. """
    book = get_object_or_404(Book, pk=pk)
    if request.method == 'POST':
        form = BookForm(request.POST, request.FILES, instance=book)
        if form.is_valid():
            form.save()
            messages.success(request, "Book was successfully updated!")
            return redirect(reverse('book:book_detail', args=[pk]))
        else:
            messages.error(
                request, "Invalid input.")
    else:
        form = BookForm(instance=book)
    return render(request, 'book/edit_book.html', {'form': form, 'book': book})


# def delete_book(request, pk):
#     """ Delete a book from the database. """
#     book = Book.objects.get(pk=pk)
#     book.delete()
#     messages.success(request, "Book was successfully deleted!")
#     return redirect('book:list_books')

book/templates/book/add_book.html
{% extends 'main.html' %}
{% block title %}Add Book{% endblock %}

{% block content %}
{% load widget_tweaks %}
<div class='flex items-center justify-center min-h-screen mb-16'>
    <div class="flex flex-col items-center w-full">
        <h1 class='mt-8 text-4xl font-bold mb-6'>Add Book</h1>
        <div class='py-8 px-8 w-[80%] lg:w-[40%] bg-slate-400 mx-auto rounded'>
            <form method='POST' enctype="multipart/form-data">
                {% csrf_token %}
                <p class="block text-slate-900 font-bold mb-2">Title:</p>
                    {% render_field form.title class+='py-2 px-2 mb-4 bg-stone-100 w-full rounded'%}
                
                <p class="block text-slate-900 font-bold mb-2">Author:</p>
                    {% render_field form.author class+='py-2 px-2 mb-4 bg-stone-100 w-full rounded'%}

                <div class='flex flex-col lg:flex-row lg:justify-between lg:gap-4'>
                    <div class='w-full'>
                        <div class='w-full'>
                            <p class="block text-slate-900 font-bold mb-2">ISBN:</p>
                            {% render_field form.isbn class+='py-2 px-2 mb-4 bg-stone-100 w-full rounded'%}
                        </div>
                    </div>
                    <div class='w-full'>
                        <div class='w-full'>
                            <p class="block text-slate-900 font-bold mb-2">Publisher:</p>
                            {% render_field form.publisher class+='py-2 px-2 mb-4 bg-stone-100 w-full rounded'%}
                        </div>
                    </div>
                </div>

                <div class='flex flex-col lg:flex-row lg:justify-between lg:gap-4'>
                    <div class='w-full'>
                        <div class='w-full'>
                            <p class="block text-slate-900 font-bold mb-2">Genre:</p>
                            {% render_field form.genre class+='py-2 px-2 mb-4 bg-stone-100 w-full rounded'%}
                        </div>
                    </div>
                    <div class='w-full'>
                        <div class='w-full'>
                            <p class="block text-slate-900 font-bold mb-2">Available Copies:</p>
                            {% render_field form.available_copies class+='py-2 px-2 mb-4 bg-stone-100 w-full rounded'%}
                        </div>
                    </div>
                </div>

                <p class="block text-slate-900 font-bold mb-2">Description:</p>
                {% render_field form.description class+='py-2 px-2 mb-4 bg-stone-100 w-full rounded'%}

                <p class="block text-slate-900 font-bold mb-2">Book Cover:</p>
                {{ form.book_cover }}
                <button type='submit' class='block mt-4 py-2 px-6 bg-slate-900 rounded text-stone-100 hover:bg-slate-950'> Add Book </button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

book/templates/book/book_detail.html
{% extends 'main.html' %}
{% block title %}{{book.title}}{% endblock %}
{% block content %}
<section class='mt-16 mb-8'>
    {% if messages %}
        {% for message in messages%}
            <p class='mb-4 text-teal-700'>{{ message }}</p>
        {% endfor %}
    {% endif %}
    <h1 class='text-3xl mb-4'>{{ book.title }}</h1>
    <div class='flex flex-col space-y-10 lg:flex-row lg:space-x-6'>
        <div class=''>
            <img src="{{book.book_cover.url}}" alt="{{ book.title }} Book Cover" class="w-1/2 lg:w-full max-h-96 object-cover">
        </div>
        <div class='flex flex-col justify-center'>
            <p><span class='text-slate-950 font-medium'>Author:</span> {{ book.author }}</p>
            <p><span class='text-slate-950 font-medium'>Genre:</span> {{ book.genre }}</p>
            <p><span class='text-slate-950 font-medium'>ISBN:</span> {{ book.isbn }}</p>
            <p><span class='text-slate-950 font-medium'>Publisher:</span> {{ book.publisher }}</p>
            <p><span class='text-slate-950 font-medium'>Available Copies:</span> {{ book.available_copies }}</p>

            <br>
            <h2 class='text-xl'>Description:</h2>
            <p>{{ book.description }}</p>
        </div>        
    </div>


    <div class='mt-2 flex flex-col lg:flex-row lg:space-x-2'>
        {% comment %} <a href="{% url 'book:delete_book' book.pk %}" class='inline-block mt-4 py-2 px-4 bg-rose-500 hover:bg-rose-700 text-white rounded'>Remove Book</a> {% endcomment %}
        <a href="{% url 'book:edit_book' book.pk %}" class='inline-block mt-4 py-2 px-4 bg-slate-700 hover:bg-slate-900 text-white rounded'>Edit Book</a>
        <a href="{% url 'transaction:return' book.id %}" class='inline-block mt-4 py-2 px-4 bg-slate-700 hover:bg-slate-900 rounded text-white'>Return a Copy</a>
        <a href="{% url 'transaction:checkout' book.id %}" class='inline-block mt-4 py-2 px-4 bg-stone-700 hover:bg-stone-900 rounded text-white'>Checkout</a>
    </div>

    <hr class='my-8 border-black'>

    <div>
        <h2 class='text-4xl mb-6'>Copies on Loans: {{ book.copies_on_loan }}</h2>
        <div class='mt-2'>
            {% for transaction in transactions %}
                {% if transaction.is_returned == False %}
                    <p><span class='text-slate-950 font-medium'>Patron:</span> <a href="{% url 'patron:patron_detail' transaction.patron.id %}" class='text-slate-500 hover:font-medium'>{{transaction.patron}}</a></p>
                    <p><span class='text-slate-950 font-medium'>Date Borrowed:</span> {{transaction.date_borrowed}}</p>
                    <p><span class='text-slate-950 font-medium'>Date Due:</span> {{transaction.date_due}}</p>
                    <br>
                {% endif %}
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

book/templates/book/edit_book.html
{% extends 'main.html' %}
{% block title %}Edit Book{% endblock %}

{% block content %}
{% load widget_tweaks %}
<div class='flex items-center justify-center min-h-screen'>
    <div class="flex flex-col items-center w-full">
        <h1 class=' text-4xl font-bold mb-6'>Edit Book</h1>
        <div class='py-8 px-8 w-2/3 lg:w-1/3 bg-slate-400 mx-auto rounded'>
            <form method='POST' enctype="multipart/form-data">
                {% csrf_token %}
                <p class="block text-slate-900 font-bold mb-2">Title:</p>
                    {% render_field form.title class+='py-2 px-2 mb-4 bg-stone-100 w-full rounded'%}
                
                <p class="block text-slate-900 font-bold mb-2">Author:</p>
                    {% render_field form.author class+='py-2 px-2 mb-4 bg-stone-100 w-full rounded'%}

                <div class='flex justify-between'>
                    <div class='w-1/2 pr-2'>
                        <div class='w-full'>
                            <p class="block text-slate-900 font-bold mb-2">ISBN:</p>
                            {% render_field form.isbn class+='py-2 px-2 mb-4 bg-stone-100 w-full rounded'%}
                        </div>
                    </div>
                    <div class='w-1/2 pl-2'>
                        <div class='w-full'>
                            <p class="block text-slate-900 font-bold mb-2">Publisher:</p>
                            {% render_field form.publisher class+='py-2 px-2 mb-4 bg-stone-100 w-full rounded'%}
                        </div>
                    </div>
                </div>

                <div class='flex justify-between'>
                    <div class='w-1/2 pr-2'>
                        <div class='w-full'>
                            <p class="block text-slate-900 font-bold mb-2">Genre:</p>
                            {% render_field form.genre class+='py-2 px-2 mb-4 bg-stone-100 w-full rounded'%}
                        </div>
                    </div>
                    <div class='w-1/2 pl-2'>
                        <div class='w-full'>
                            <p class="block text-slate-900 font-bold mb-2">Available Copies:</p>
                            {% render_field form.available_copies class+='py-2 px-2 mb-4 bg-stone-100 w-full rounded'%}
                        </div>
                    </div>
                </div>

                <p class="block text-slate-900 font-bold mb-2">Description:</p>
                {% render_field form.description class+='py-2 px-2 mb-4 bg-stone-100 w-full rounded'%}

                <p class="block text-slate-900 font-bold mb-2">Book Cover:</p>
                {{ form.book_cover }}
                <button type='submit' class='block mt-4 py-2 px-6 bg-slate-900 rounded text-stone-100 hover:bg-slate-950'> Edit Book </button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

book/templates/book/list_books.html
{% extends 'main.html' %}
{% block title %}Books{% endblock %}

{% block content %}
<h1 class='text-5xl mt-16 mb-4'>Available Books</h1>
<a href="{% url 'book:add_book' %}" class='inline-block mt-4 mb-8 py-2 px-6 text-white bg-teal-700 hover:bg-teal-900 rounded'>Add Book</a>
{% for message in messages %}
    <div class='font-semibold'>{{message}}</div>
{% endfor %}
<div class='flex flex-col lg:flex-row lg:justify-between mb-10'>
    <section class='w-full lg:w-2/5'>        
        {% for book in page_obj %}
        <div class='flex space-x-4'>
            
            <div class='w-1/2'>
                <h3 class='text-2xl mb-2'><a href="{% url 'book:book_detail' book.pk %}" class='hover:text-slate-600'>{{ book.title }}</a></h3>
                <p><span class='text-slate-900 font-medium'>Author:</span> {{ book.author }}</p>
                <p><span class='text-slate-900 font-medium'>Genre:</span> {{ book.genre }}</p>
                {% if book.available_copies <= 0 %}
                    <p class='text-rose-600 font-medium'>Available Copies: {{ book.available_copies }}</p>
                {% else %}
                    <p><span class='text-slate-900 font-medium'>Available Copies:</span> {{ book.available_copies }}</p>
                {% endif %}
            </div>

            <div class=''>
                <img src="{{book.book_cover.url}}" alt="{{ book.title }} Book Cover" class="w-full h-32 object-scale-down">
            </div>
        </div>
        <a href="{% url 'transaction:return' book.id %}" class='inline-block py-2 px-4 bg-slate-700 hover:bg-slate-900 rounded text-white'>Return a Copy</a>
        <a href="{% url 'transaction:checkout' book.id %}" class='inline-block mt-4 py-2 px-4 bg-stone-700 hover:bg-stone-900 rounded text-white'>Checkout</a>
            <hr class='border border-black mt-4 mb-4'>
        {% endfor %}
        <div id='pagination' class="flex justify-between mt-10 mb-10">
            {% if page_obj.has_previous %}
                <div class='space-x-4'>
                    <a href="?page=1">« first</a>
                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                </div>                    
            {% endif %}
        
            <span>
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </span>
        
            {% if page_obj.has_next %}
                <div class='space-x-4'>
                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">last »</a>
                </div>
            {% endif %}
        </div>
    </section>
    <section class='w-full lg:w-1/4'>
        <div>
            <h2 class='text-2xl'>Search</h2>
            <form action="" method="GET">
                <input type="text" name='q' placeholder='Enter title, author, genre, isbn...' value='{{request.GET.q}}' class='w-full bg-slate-300 mt-2 py-2 px-2 rounded'>
            </form>
        </div>
        

        <div class='mt-6'>
            <h2 class='text-2xl'>Browse by Genre</h2>
            <ul class='mt-4 list-disc list-inside'>
                <li><a href='{% url "book:list_books" %}?q=fiction' class='hover:text-slate-500 hover:font-medium'>Fiction</a></li>
                <li><a href='{% url "book:list_books" %}?q=adventure' class='hover:text-slate-500 hover:font-medium'>Adventure</a></li>
                <li><a href='{% url "book:list_books" %}?q=fantasy' class='hover:text-slate-500 hover:font-medium'>Fantasy</a></li>
                <li><a href='{% url "book:list_books" %}?q=historical' class='hover:text-slate-500 hover:font-medium'>Historical</a></li>
                <li><a href='{% url "book:list_books" %}?q=travel' class='hover:text-slate-500 hover:font-medium'>Travel</a></li>
                <li><a href='{% url "book:list_books" %}?q=business' class='hover:text-slate-500 hover:font-medium'>Business</a></li>
                <li><a href='{% url "book:list_books" %}?q=science-fiction' class='hover:text-slate-500 hover:font-medium'>Science Fiction</a></li>
                <li><a href='{% url "book:list_books" %}?q=romance' class='hover:text-slate-500 hover:font-medium'>Romance</a></li>
                <li><a href='{% url "book:list_books" %}?q=mystery' class='hover:text-slate-500 hover:font-medium'>Mystery</a></li>
                <li><a href='{% url "book:list_books" %}?q=drama' class='hover:text-slate-500 hover:font-medium'>Drama</a></li>
                <li><a href='{% url "book:list_books" %}?q=biography' class='hover:text-slate-500 hover:font-medium'>Biography</a></li>
                <li><a href='{% url "book:list_books" %}?q=children' class='hover:text-slate-500 hover:font-medium'>Children's</a></li>
                <li><a href='{% url "book:list_books" %}?q=history' class='hover:text-slate-500 hover:font-medium'>History</a></li>
                <li><a href='{% url "book:list_books" %}?q=non-fiction' class='hover:text-slate-500 hover:font-medium'>Non-Fiction</a></li>
            </ul>           
        </div>
    </section>
</div>
{% endblock %}